/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.PSClass;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel David Ortiz
 */
public class PSForm extends javax.swing.JFrame {

    PSClass psClass;
    
    public PSForm() {
        initComponents();
        
        psClass = new PSClass();
        psClass.IngresoDatos();
        psClass.lblColores(txtRB, txtBA, txtBV, txtTotal);
        this.jTextArea1.setText("S = {" + psClass.txtMuestra() + "}");
        
        
        this.jTextArea1.setLineWrap(true);
        this.jTextArea1.setWrapStyleWord(true);
                
        psClass.eventos();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelMuestra = new javax.swing.JPanel();
        lblBR = new javax.swing.JLabel();
        txtRB = new javax.swing.JLabel();
        lblBA = new javax.swing.JLabel();
        txtBA = new javax.swing.JLabel();
        lblBV = new javax.swing.JLabel();
        txtBV = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblEM = new javax.swing.JLabel();
        panelEv1 = new javax.swing.JPanel();
        lblEvR = new javax.swing.JLabel();
        txtEvR = new javax.swing.JLabel();
        lblEvV = new javax.swing.JLabel();
        txtEvV = new javax.swing.JLabel();
        lblEvA = new javax.swing.JLabel();
        txtEvA = new javax.swing.JLabel();
        panelEv2 = new javax.swing.JPanel();
        lblEvNR = new javax.swing.JLabel();
        txtEvNR = new javax.swing.JLabel();
        lblEvNA = new javax.swing.JLabel();
        txtEvNA = new javax.swing.JLabel();
        lblEvNV = new javax.swing.JLabel();
        txtEvNV = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTitulo.setLayout(new java.awt.GridLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Probabilidad simple");
        panelTitulo.add(jLabel2);

        panelMuestra.setLayout(new java.awt.GridLayout(4, 2, 10, 0));

        lblBR.setText("Bolas rojas");
        panelMuestra.add(lblBR);

        txtRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMuestra.add(txtRB);

        lblBA.setText("Bolas amarillas");
        panelMuestra.add(lblBA);

        txtBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMuestra.add(txtBA);

        lblBV.setText("Bolas verdes");
        panelMuestra.add(lblBV);

        txtBV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMuestra.add(txtBV);

        lblTotal.setText("Total");
        panelMuestra.add(lblTotal);

        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMuestra.add(txtTotal);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblEM.setText("Espacio Muestral");

        panelEv1.setPreferredSize(new java.awt.Dimension(240, 154));
        panelEv1.setRequestFocusEnabled(false);
        panelEv1.setLayout(new java.awt.GridLayout(3, 2, 10, 0));

        lblEvR.setText("Sea roja");
        panelEv1.add(lblEvR);

        txtEvR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv1.add(txtEvR);

        lblEvV.setText("Sea verde");
        panelEv1.add(lblEvV);

        txtEvV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv1.add(txtEvV);

        lblEvA.setText("Sea amarilla");
        panelEv1.add(lblEvA);

        txtEvA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv1.add(txtEvA);

        panelEv2.setPreferredSize(new java.awt.Dimension(240, 0));
        panelEv2.setLayout(new java.awt.GridLayout(3, 2, 10, 0));

        lblEvNR.setText("No sea roja");
        panelEv2.add(lblEvNR);

        txtEvNR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv2.add(txtEvNR);

        lblEvNA.setText("No sea amarilla");
        panelEv2.add(lblEvNA);

        txtEvNA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv2.add(txtEvNA);

        lblEvNV.setText("No sea verde");
        panelEv2.add(lblEvNV);

        txtEvNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEv2.add(txtEvNV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelEv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEv2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBA;
    private javax.swing.JLabel lblBR;
    private javax.swing.JLabel lblBV;
    private javax.swing.JLabel lblEM;
    private javax.swing.JLabel lblEvA;
    private javax.swing.JLabel lblEvNA;
    private javax.swing.JLabel lblEvNR;
    private javax.swing.JLabel lblEvNV;
    private javax.swing.JLabel lblEvR;
    private javax.swing.JLabel lblEvV;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelEv1;
    private javax.swing.JPanel panelEv2;
    private javax.swing.JPanel panelMuestra;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel txtBA;
    private javax.swing.JLabel txtBV;
    private javax.swing.JLabel txtEvA;
    private javax.swing.JLabel txtEvNA;
    private javax.swing.JLabel txtEvNR;
    private javax.swing.JLabel txtEvNV;
    private javax.swing.JLabel txtEvR;
    private javax.swing.JLabel txtEvV;
    private javax.swing.JLabel txtRB;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

}
